# Installing a running a the app from my git repo

- hosts: web
  gather_facts: true
  become: true

  tasks:
  - name: Installing npm
    apt: pkg=npm state=present
    become_user: root
  - name: Cloning GIT
    git:
      repo: https://github.com/GNUKalashnikov/starter-code.git
      dest: /home/vagrant/repo
      clone: yes
      update: yes
  - name: installing pm2
    command: npm install pm2 -g
    become_user: root
  - name: starting the app
    command: pm2 start app.js
    args:
      chdir: repo/app/

